
server:
  port: 8888
  servlet:
    context-path: /shiro-test


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro-test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0 # Redis数据库索引（默认为0）
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞时间（使用负值表示没有限制）
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    timeout: 3000 #连接超时时间

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

jwt:
  # token签名
  sing: shiro-test
  # token过期时间（分钟）
  expire: 1440
  # 小于多少时间时自动刷新 token（分钟）
  refreshTime: 10